name: Guardrail - DataStream import

on:
  pull_request:
  push:
    branches: [ main, "**" ]

jobs:
  guardrail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate DataStream import usage
        run: |
          set -euo pipefail
          # Procura imports de "@/components/ui/data-stream" SEM o sufixo ".client"
          if grep -R -nP \
            --include='*.ts' --include='*.tsx' --include='*.js' --include='*.jsx' \
            --exclude-dir=node_modules --exclude-dir=.next --exclude-dir=.github \
            --exclude='.eslintrc.js' \
            "@/components/ui/data-stream(?!\.client)['\"]" . ; then
            echo "Import inválido de data-stream sem .client detectado"
            exit 1
          else
            echo "OK: nenhum import inválido encontrado"
          fi
