name: Health Ping

on:
  schedule:
    - cron: '*/10 * * * *' # a cada 10 min (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit CRSET health cron
        run: |
          set -e
          echo "Pinging /api/cron/health @ $(date -u)"
          curl -sS "https://crsetsolutions.com/api/cron/health" | tee response.json
          echo "OK"
