name: Health Check (daily)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no build needed)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Smoke check (prod homepage)
        env:
          BASE_URL: https://crsetsolutions.com
        run: |
          set -euo pipefail
          echo "Checking $BASE_URL/ ..."
          for i in {1..5}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$BASE_URL/")
            echo "Attempt $i: status=$code"
            if [ "$code" -eq 200 ]; then
              echo "OK"; exit 0
            fi
            sleep 5
          done
          echo "Health check failed"; exit 1

      - name: Observe /demo redirect (non-blocking)
        if: always()
        continue-on-error: true
        env:
          BASE_URL: https://crsetsolutions.com
        run: |
          set -euo pipefail
          echo "HEAD $BASE_URL/demo"
          curl -sI "$BASE_URL/demo" | sed -n '1p;/^location:/Ip'
