name: Health Ping
on:
  schedule:
    - cron: '*/30 * * * *'   # a cada 30min
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check /api/cron/health
        run: |
          URL="https://crsetsolutions.com/api/cron/health?src=ci"
          echo "Pinging $URL"
          curl --fail --silent --show-error \
               --max-time 20 --retry 2 --retry-delay 2 --retry-connrefused \
               -H "accept: application/json" "$URL"
