name: Health Ping
on:
  schedule:
    - cron: '*/30 * * * *'   # corre de 30 em 30 min
  workflow_dispatch:          # podes correr manualmente no UI
jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      URL: https://crset-solutions-frontend.vercel.app/api/telemetry?src=ci?src=ci
      CRON_TOKEN: ${{ secrets.CRON_SECRET }}   # cria este secret com o mesmo valor do CRON_SECRET do Vercel
    steps:
      - name: Check /api/cron/health (header auth)
        run: |
          set -euo pipefail
          curl --fail --silent --show-error \
            -H "x-webhook-secret: $CRON_TOKEN" \
            "$URL" >/dev/null
