name: Health Ping
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      HEALTH_URL: https://crset-solutions-frontend-m0641as9e-joao-fonsecas-projects.vercel.app/api/cron/health
      CRON_TOKEN: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Check /api/cron/health (header auth)
        run: |
          set -e
          URL="$HEALTH_URL?src=ci"
          echo "Pinging $URL"
          curl -fsS -H "x-webhook-secret: $CRON_TOKEN" "$URL" >/dev/null
